// <auto-generated />
namespace DB
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0-preview3-19553-01")]
    public sealed partial class sprint10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sprint10));
        
        string IMigrationMetadata.Id
        {
            get { return "201912081551193_sprint10"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
